export interface CountryInfo {
  name: string;
  currency: string;
  code: string;
  flag: string;
}

export const ALL_COUNTRIES: CountryInfo[] = [
  { name: "Afghanistan", currency: "AFN", code: "AF", flag: "🇦🇫" },
  { name: "Afrique du Sud", currency: "ZAR", code: "ZA", flag: "🇿🇦" },
  { name: "Albanie", currency: "ALL", code: "AL", flag: "🇦🇱" },
  { name: "Algérie", currency: "DZD", code: "DZ", flag: "🇩🇿" },
  { name: "Allemagne", currency: "EUR", code: "DE", flag: "🇩🇪" },
  { name: "Andorre", currency: "EUR", code: "AD", flag: "🇦🇩" },
  { name: "Angola", currency: "AOA", code: "AO", flag: "🇦🇴" },
  { name: "Antigua-et-Barbuda", currency: "XCD", code: "AG", flag: "🇦🇬" },
  { name: "Arabie Saoudite", currency: "SAR", code: "SA", flag: "🇸🇦" },
  { name: "Argentine", currency: "ARS", code: "AR", flag: "🇦🇷" },
  { name: "Arménie", currency: "AMD", code: "AM", flag: "🇦🇲" },
  { name: "Australie", currency: "AUD", code: "AU", flag: "🇦🇺" },
  { name: "Autriche", currency: "EUR", code: "AT", flag: "🇦🇹" },
  { name: "Azerbaïdjan", currency: "AZN", code: "AZ", flag: "🇦🇿" },
  { name: "Bahamas", currency: "BSD", code: "BS", flag: "🇧🇸" },
  { name: "Bahreïn", currency: "BHD", code: "BH", flag: "🇧🇭" },
  { name: "Bangladesh", currency: "BDT", code: "BD", flag: "🇧🇩" },
  { name: "Barbade", currency: "BBD", code: "BB", flag: "🇧🇧" },
  { name: "Belgique", currency: "EUR", code: "BE", flag: "🇧🇪" },
  { name: "Belize", currency: "BZD", code: "BZ", flag: "🇧🇿" },
  { name: "Bénin", currency: "XOF", code: "BJ", flag: "🇧🇯" },
  { name: "Bhoutan", currency: "BTN", code: "BT", flag: "🇧🇹" },
  { name: "Biélorussie", currency: "BYN", code: "BY", flag: "🇧🇾" },
  { name: "Birmanie (Myanmar)", currency: "MMK", code: "MM", flag: "🇲🇲" },
  { name: "Bolivie", currency: "BOB", code: "BO", flag: "🇧🇴" },
  { name: "Bosnie-Herzégovine", currency: "BAM", code: "BA", flag: "🇧🇦" },
  { name: "Botswana", currency: "BWP", code: "BW", flag: "🇧🇼" },
  { name: "Brésil", currency: "BRL", code: "BR", flag: "🇧🇷" },
  { name: "Brunei", currency: "BND", code: "BN", flag: "🇧🇳" },
  { name: "Bulgarie", currency: "BGN", code: "BG", flag: "🇧🇬" },
  { name: "Burkina Faso", currency: "XOF", code: "BF", flag: "🇧🇫" },
  { name: "Burundi", currency: "BIF", code: "BI", flag: "🇧🇮" },
  { name: "Cambodge", currency: "KHR", code: "KH", flag: "🇰🇭" },
  { name: "Cameroun", currency: "XAF", code: "CM", flag: "🇨🇲" },
  { name: "Canada", currency: "CAD", code: "CA", flag: "🇨🇦" },
  { name: "Cap-Vert", currency: "CVE", code: "CV", flag: "🇨🇻" },
  { name: "Centrafrique", currency: "XAF", code: "CF", flag: "🇨🇫" },
  { name: "Chili", currency: "CLP", code: "CL", flag: "🇨🇱" },
  { name: "Chine", currency: "CNY", code: "CN", flag: "🇨🇳" },
  { name: "Chypre", currency: "EUR", code: "CY", flag: "🇨🇾" },
  { name: "Colombie", currency: "COP", code: "CO", flag: "🇨🇴" },
  { name: "Comores", currency: "KMF", code: "KM", flag: "🇰🇲" },
  { name: "Congo-Brazzaville", currency: "XAF", code: "CG", flag: "🇨🇬" },
  { name: "Congo-Kinshasa (RDC)", currency: "CDF", code: "CD", flag: "🇨🇩" },
  { name: "Corée du Nord", currency: "KPW", code: "KP", flag: "🇰🇵" },
  { name: "Corée du Sud", currency: "KRW", code: "KR", flag: "🇰🇷" },
  { name: "Costa Rica", currency: "CRC", code: "CR", flag: "🇨🇷" },
  { name: "Côte d'Ivoire", currency: "XOF", code: "CI", flag: "🇨🇮" },
  { name: "Croatie", currency: "EUR", code: "HR", flag: "🇭🇷" },
  { name: "Cuba", currency: "CUP", code: "CU", flag: "🇨🇺" },
  { name: "Danemark", currency: "DKK", code: "DK", flag: "🇩🇰" },
  { name: "Djibouti", currency: "DJF", code: "DJ", flag: "🇩🇯" },
  { name: "Dominique", currency: "XCD", code: "DM", flag: "🇩🇲" },
  { name: "Égypte", currency: "EGP", code: "EG", flag: "🇪🇬" },
  { name: "Émirats Arabes Unis", currency: "AED", code: "AE", flag: "🇦🇪" },
  { name: "Équateur", currency: "USD", code: "EC", flag: "🇪🇨" },
  { name: "Érythrée", currency: "ERN", code: "ER", flag: "🇪🇷" },
  { name: "Espagne", currency: "EUR", code: "ES", flag: "🇪🇸" },
  { name: "Estonie", currency: "EUR", code: "EE", flag: "🇪🇪" },
  { name: "Eswatini (Swaziland)", currency: "SZL", code: "SZ", flag: "🇸🇿" },
  { name: "États-Unis", currency: "USD", code: "US", flag: "🇺🇸" },
  { name: "Éthiopie", currency: "ETB", code: "ET", flag: "🇪🇹" },
  { name: "Fidji", currency: "FJD", code: "FJ", flag: "🇫🇯" },
  { name: "Finlande", currency: "EUR", code: "FI", flag: "🇫🇮" },
  { name: "France", currency: "EUR", code: "FR", flag: "🇫🇷" },
  { name: "Gabon", currency: "XAF", code: "GA", flag: "🇬🇦" },
  { name: "Gambie", currency: "GMD", code: "GM", flag: "🇬🇲" },
  { name: "Géorgie", currency: "GEL", code: "GE", flag: "🇬🇪" },
  { name: "Ghana", currency: "GHS", code: "GH", flag: "🇬🇭" },
  { name: "Grèce", currency: "EUR", code: "GR", flag: "🇬🇷" },
  { name: "Grenade", currency: "XCD", code: "GD", flag: "🇬🇩" },
  { name: "Guatemala", currency: "GTQ", code: "GT", flag: "🇬🇹" },
  { name: "Guinée", currency: "GNF", code: "GN", flag: "🇬🇳" },
  { name: "Guinée équatoriale", currency: "XAF", code: "GQ", flag: "🇬🇶" },
  { name: "Guinée-Bissau", currency: "XOF", code: "GW", flag: "🇬🇼" },
  { name: "Guyana", currency: "GYD", code: "GY", flag: "🇬🇾" },
  { name: "Haïti", currency: "HTG", code: "HT", flag: "🇭🇹" },
  { name: "Honduras", currency: "HNL", code: "HN", flag: "🇭🇳" },
  { name: "Hongrie", currency: "HUF", code: "HU", flag: "🇭🇺" },
  { name: "Inde", currency: "INR", code: "IN", flag: "🇮🇳" },
  { name: "Indonésie", currency: "IDR", code: "ID", flag: "🇮🇩" },
  { name: "Irak", currency: "IQD", code: "IQ", flag: "🇮🇶" },
  { name: "Iran", currency: "IRR", code: "IR", flag: "🇮🇷" },
  { name: "Irlande", currency: "EUR", code: "IE", flag: "🇮🇪" },
  { name: "Islande", currency: "ISK", code: "IS", flag: "🇮🇸" },
  { name: "Israël", currency: "ILS", code: "IL", flag: "🇮🇱" },
  { name: "Italie", currency: "EUR", code: "IT", flag: "🇮🇹" },
  { name: "Jamaïque", currency: "JMD", code: "JM", flag: "🇯🇲" },
  { name: "Japon", currency: "JPY", code: "JP", flag: "🇯🇵" },
  { name: "Jordanie", currency: "JOD", code: "JO", flag: "🇯🇴" },
  { name: "Kazakhstan", currency: "KZT", code: "KZ", flag: "🇰🇿" },
  { name: "Kenya", currency: "KES", code: "KE", flag: "🇰🇪" },
  { name: "Kirghizistan", currency: "KGS", code: "KG", flag: "🇰🇬" },
  { name: "Kiribati", currency: "AUD", code: "KI", flag: "🇰🇮" },
  { name: "Koweït", currency: "KWD", code: "KW", flag: "🇰🇼" },
  { name: "Laos", currency: "LAK", code: "LA", flag: "🇱🇦" },
  { name: "Lesotho", currency: "LSL", code: "LS", flag: "🇱🇸" },
  { name: "Lettonie", currency: "EUR", code: "LV", flag: "🇱🇻" },
  { name: "Liban", currency: "LBP", code: "LB", flag: "🇱🇧" },
  { name: "Liberia", currency: "LRD", code: "LR", flag: "🇱🇷" },
  { name: "Libye", currency: "LYD", code: "LY", flag: "🇱🇾" },
  { name: "Liechtenstein", currency: "CHF", code: "LI", flag: "🇱🇮" },
  { name: "Lituanie", currency: "EUR", code: "LT", flag: "🇱🇹" },
  { name: "Luxembourg", currency: "EUR", code: "LU", flag: "🇱🇺" },
  { name: "Macédoine du Nord", currency: "MKD", code: "MK", flag: "🇲🇰" },
  { name: "Madagascar", currency: "MGA", code: "MG", flag: "🇲🇬" },
  { name: "Malaisie", currency: "MYR", code: "MY", flag: "🇲🇾" },
  { name: "Malawi", currency: "MWK", code: "MW", flag: "🇲🇼" },
  { name: "Maldives", currency: "MVR", code: "MV", flag: "🇲🇻" },
  { name: "Mali", currency: "XOF", code: "ML", flag: "🇲🇱" },
  { name: "Malte", currency: "EUR", code: "MT", flag: "🇲🇹" },
  { name: "Maroc", currency: "MAD", code: "MA", flag: "🇲🇦" },
  { name: "Maurice", currency: "MUR", code: "MU", flag: "🇲🇺" },
  { name: "Mauritanie", currency: "MRU", code: "MR", flag: "🇲🇷" },
  { name: "Mexique", currency: "MXN", code: "MX", flag: "🇲🇽" },
  { name: "Micronésie", currency: "USD", code: "FM", flag: "🇫🇲" },
  { name: "Moldavie", currency: "MDL", code: "MD", flag: "🇲🇩" },
  { name: "Monaco", currency: "EUR", code: "MC", flag: "🇲🇨" },
  { name: "Mongolie", currency: "MNT", code: "MN", flag: "🇲🇳" },
  { name: "Monténégro", currency: "EUR", code: "ME", flag: "🇲🇪" },
  { name: "Mozambique", currency: "MZN", code: "MZ", flag: "🇲🇿" },
  { name: "Namibie", currency: "NAD", code: "NA", flag: "🇳🇦" },
  { name: "Nauru", currency: "AUD", code: "NR", flag: "🇳🇷" },
  { name: "Népal", currency: "NPR", code: "NP", flag: "🇳🇵" },
  { name: "Nicaragua", currency: "NIO", code: "NI", flag: "🇳🇮" },
  { name: "Niger", currency: "XOF", code: "NE", flag: "🇳🇪" },
  { name: "Nigeria", currency: "NGN", code: "NG", flag: "🇳🇬" },
  { name: "Norvège", currency: "NOK", code: "NO", flag: "🇳🇴" },
  { name: "Nouvelle-Zélande", currency: "NZD", code: "NZ", flag: "🇳🇿" },
  { name: "Oman", currency: "OMR", code: "OM", flag: "🇴🇲" },
  { name: "Ouganda", currency: "UGX", code: "UG", flag: "🇺🇬" },
  { name: "Ouzbékistan", currency: "UZS", code: "UZ", flag: "🇺🇿" },
  { name: "Pakistan", currency: "PKR", code: "PK", flag: "🇵🇰" },
  { name: "Palaos", currency: "USD", code: "PW", flag: "🇵🇼" },
  { name: "Palestine", currency: "ILS", code: "PS", flag: "🇵🇸" },
  { name: "Panama", currency: "USD", code: "PA", flag: "🇵🇦" },
  { name: "Papouasie-Nouvelle-Guinée", currency: "PGK", code: "PG", flag: "🇵🇬" },
  { name: "Paraguay", currency: "PYG", code: "PY", flag: "🇵🇾" },
  { name: "Pays-Bas", currency: "EUR", code: "NL", flag: "🇳🇱" },
  { name: "Pérou", currency: "PEN", code: "PE", flag: "🇵🇪" },
  { name: "Philippines", currency: "PHP", code: "PH", flag: "🇵🇭" },
  { name: "Pologne", currency: "PLN", code: "PL", flag: "🇵🇱" },
  { name: "Portugal", currency: "EUR", code: "PT", flag: "🇵🇹" },
  { name: "Qatar", currency: "QAR", code: "QA", flag: "🇶🇦" },
  { name: "République Centrafricaine", currency: "XAF", code: "CF", flag: "🇨🇫" },
  { name: "République Dominicaine", currency: "DOP", code: "DO", flag: "🇩🇴" },
  { name: "République Tchèque", currency: "CZK", code: "CZ", flag: "🇨🇿" },
  { name: "Roumanie", currency: "RON", code: "RO", flag: "🇷🇴" },
  { name: "Royaume-Uni", currency: "GBP", code: "GB", flag: "🇬🇧" },
  { name: "Russie", currency: "RUB", code: "RU", flag: "🇷🇺" },
  { name: "Rwanda", currency: "RWF", code: "RW", flag: "🇷🇼" },
  { name: "Saint-Christophe-et-Niévès", currency: "XCD", code: "KN", flag: "🇰🇳" },
  { name: "Saint-Marin", currency: "EUR", code: "SM", flag: "🇸🇲" },
  { name: "Saint-Vincent-et-les-Grenadines", currency: "XCD", code: "VC", flag: "🇻🇨" },
  { name: "Sainte-Lucie", currency: "XCD", code: "LC", flag: "🇱🇨" },
  { name: "Salomon", currency: "SBD", code: "SB", flag: "🇸🇧" },
  { name: "Samoa", currency: "WST", code: "WS", flag: "🇼🇸" },
  { name: "Sao Tomé-et-Principe", currency: "STN", code: "ST", flag: "🇸🇹" },
  { name: "Sénégal", currency: "XOF", code: "SN", flag: "🇸🇳" },
  { name: "Serbie", currency: "RSD", code: "RS", flag: "🇷🇸" },
  { name: "Seychelles", currency: "SCR", code: "SC", flag: "🇸🇨" },
  { name: "Sierra Leone", currency: "SLL", code: "SL", flag: "🇸🇱" },
  { name: "Singapour", currency: "SGD", code: "SG", flag: "🇸🇬" },
  { name: "Slovaquie", currency: "EUR", code: "SK", flag: "🇸🇰" },
  { name: "Slovénie", currency: "EUR", code: "SI", flag: "🇸🇮" },
  { name: "Somalie", currency: "SOS", code: "SO", flag: "🇸🇴" },
  { name: "Soudan", currency: "SDG", code: "SD", flag: "🇸🇩" },
  { name: "Soudan du Sud", currency: "SSP", code: "SS", flag: "🇸🇸" },
  { name: "Sri Lanka", currency: "LKR", code: "LK", flag: "🇱🇰" },
  { name: "Suède", currency: "SEK", code: "SE", flag: "🇸🇪" },
  { name: "Suisse", currency: "CHF", code: "CH", flag: "🇨🇭" },
  { name: "Suriname", currency: "SRD", code: "SR", flag: "🇸🇷" },
  { name: "Syrie", currency: "SYP", code: "SY", flag: "🇸🇾" },
  { name: "Tadjikistan", currency: "TJS", code: "TJ", flag: "🇹🇯" },
  { name: "Taïwan", currency: "TWD", code: "TW", flag: "🇹🇼" },
  { name: "Tanzanie", currency: "TZS", code: "TZ", flag: "🇹🇿" },
  { name: "Tchad", currency: "XAF", code: "TD", flag: "🇹🇩" },
  { name: "Thaïlande", currency: "THB", code: "TH", flag: "🇹🇭" },
  { name: "Timor oriental", currency: "USD", code: "TL", flag: "🇹🇱" },
  { name: "Togo", currency: "XOF", code: "TG", flag: "🇹🇬" },
  { name: "Tonga", currency: "TOP", code: "TO", flag: "🇹🇴" },
  { name: "Trinité-et-Tobago", currency: "TTD", code: "TT", flag: "🇹🇹" },
  { name: "Tunisie", currency: "TND", code: "TN", flag: "🇹🇳" },
  { name: "Turkménistan", currency: "TMT", code: "TM", flag: "🇹🇲" },
  { name: "Turquie", currency: "TRY", code: "TR", flag: "🇹🇷" },
  { name: "Tuvalu", currency: "AUD", code: "TV", flag: "🇹🇻" },
  { name: "Ukraine", currency: "UAH", code: "UA", flag: "🇺🇦" },
  { name: "Uruguay", currency: "UYU", code: "UY", flag: "🇺🇾" },
  { name: "Vanuatu", currency: "VUV", code: "VU", flag: "🇻🇺" },
  { name: "Vatican", currency: "EUR", code: "VA", flag: "🇻🇦" },
  { name: "Venezuela", currency: "VES", code: "VE", flag: "🇻🇪" },
  { name: "Viêt Nam", currency: "VND", code: "VN", flag: "🇻🇳" },
  { name: "Yémen", currency: "YER", code: "YE", flag: "🇾🇪" },
  { name: "Zambie", currency: "ZMW", code: "ZM", flag: "🇿🇲" },
  { name: "Zimbabwe", currency: "ZWG", code: "ZW", flag: "🇿🇼" }
];

export function getCurrencyForCountry(countryName: string): string {
  const match = ALL_COUNTRIES.find(
    c => c.name.toLowerCase() === countryName.toLowerCase()
  );
  return match ? match.currency : "USD";
}
